#!/bin/sh
#
# sng_regress -- regression test harness for sng
#

trap "rm -f /tmp/*$$.[ps]ng" 0 1 2 15 

for file in $*
do
    case $file in
    *.png)
        # echo "Regression-testing against PNG file \`$file'"
        if sng <${file} >/tmp/decompiled$$.sng
        then
	    :
	else
            echo "$file: decompilation of the test PNG failed.";
            exit 1
        fi
        if sng </tmp/decompiled$$.sng >/tmp/decompiled$$.png
        then
	    :
	else
            echo "$file: recompilation of the decompiled form failed.";
            exit 1
        fi
        if sng </tmp/decompiled$$.png >/tmp/canonicalized$$.sng
        then
	    :
	else
            echo "$file: generation of the canonicalized form failed.";
            exit 1
        fi
        if sng </tmp/canonicalized$$.sng >/tmp/canonicalized$$.png
        then
	    :
	else
            echo "$file: recompilation of the canonicalized form failed.";
            exit 1
        fi
        if cmp -s /tmp/decompiled$$.png /tmp/canonicalized$$.png
        then
	    echo "$file: regression test passed."
	else
            echo "$file: decompiled and canonicalized versions differ.";
            exit 1
        fi
    ;;
    *.sng)
        # echo "Regression-testing against SNG file \`$file'"
        # Make a canonicalized version of the test file
        # Regenerate canonicalized version from its PNG
        # Diff the two
        if sng <${file} >/tmp/test$$.png
        then
	    :
	else
            echo "$file: compilation of the test SNG failed.";
            exit 1
        fi
        if sng </tmp/test$$.png >/tmp/canonicalized$$.sng
        then
	    :
	else
            echo "$file: generation of the canonicalized form failed.";
            exit 1
        fi
        if sng </tmp/canonicalized$$.sng >/tmp/canonicalized$$.png
        then
	    :
	else
            echo "$file: recompilation of the canonicalized form failed.";
            exit 1
        fi
        if sng </tmp/canonicalized$$.png >/tmp/decompiled$$.sng
        then
	    :
	else
            echo "$file: decompilation of the canonicalized form failed.";
            exit 1
        fi
        if diff -c /tmp/canonicalized$$.sng /tmp/decompiled$$.sng
        then
	    echo "$file: regression test passed."
	else
            echo "$file: decompiled and canonicalized versions differ.";
            exit 1
        fi
    ;;
    *)
        echo "Non-PNG, non-SNG file \`$file' ignored"
    ;;
    esac
done

# sng_regress ends here



