#!/bin/sh

version=`sed -n '/VERSION *= *\(.*\)/s//\1/p' <Makefile`
echo "Uploading sng version ${version}"

# if [ ! -f sng-${version}-1.i386.rpm ]
# then
# 	echo "sng-${version}-1.i386.rpm is missing"
# 	exit 1
# fi
# if [ ! -f sng-${version}-1.src.rpm ]
# then
# 	echo "sng-${version}-1.src.rpm is missing"
# 	exit 1
# fi
make zip
indexgen.sh
lsmgen.sh

echo "Uploading to SourceForge"
FTP=esr@shell.sourceforge.net:/home/groups/ftp/pub/sng/
HTML=esr@shell.sourceforge.net:/home/groups/sng/htdocs
# First, copy to SourceForge website
scp sng-${version}.tar.gz $FTP
scp sng-${version}.zip $FTP
scp index.html $HTML
scp NEWS $FTP
echo "Upload to SourceForge complete"

lftp <<EOF
# First, copy to primary website
#open $WWWHOST
#cd $WWWDIR/sng
#put sng-${version}.tar.gz
## put sng-${version}-1.i386.rpm
## put sng-${version}-1.src.rpm
#put sng-${version}.zip
#put index.html
#put NEWS
#lcd ..
#put software.html
#lcd sng
#close
#echo "Upload to tuxedo complete"

# Next, copy to locke FTP directory 
open locke.ccil.org
cd ~ftp/pub/esr/
put sng-${version}.tar.gz
# put sng-${version}-1.i386.rpm
# put sng-${version}-1.src.rpm
close
echo "Upload to locke complete"

# Next, submit to Metalab
open -u anonymous,esr@snark.thyrsus.com metalab.unc.edu
cd incoming/Linux
put sng-${version}.tar.gz
# put sng-${version}-1.i386.rpm
# put sng-${version}-1.src.rpm
put sng.lsm
close
echo "Upload to Metalab complete"

# Finally, ship to the Red Hat contrib directory
# open incoming.redhat.com
# cd libc6
# put sng-${version}-1.i386.rpm
# put sng-${version}-1.src.rpm
# close
# echo "Upload to Red Hat complete"

EOF

echo "sng uploaded"


