#!/bin/sh

version=`sed -n '/VERSION *= *\(.*\)/s//\1/p' <Makefile`
echo "Uploading sng version ${version}"

echo "Uploading to SourceForge"
FTP=upload.sourceforge.net
#HTML=esr@shell.sourceforge.net:/home/groups/s/sn/sng/htdocs
# First, copy to SourceForge website
lftp <<EOF
open -u anonymous,esr@snark.thyrsus.com $FTP
cd /incoming
put sng-${version}.tar.gz $FTP
put sng-${version}.zip $FTP
put sng-${version}-1.i386.rpm $FTP
put sng-${version}-1.src.rpm $FTP
put index.html $HTML
#put NEWS $FTP
EOF
echo "Upload to SourceForge complete"


